on: push
name: dabeladl public changes
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
        with:
          lfs: true
          fetch-depth: 100
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.dabeladl.com
          protocol: ftps
          port: 21
          username: dabeladl
          password: ${{ secrets.ftp_password }}
          server-dir: /public_html/
          local-dir: ./public/
          dangerous-clean-slate: false
          timeout: 600000
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            vendor/**
            index.php
            .htaccess
            uploads
            res_admin/images/**